[tox]
envlist = py310, lint, docs

[testenv]
deps = pytest
commands = pytest

[testenv:lint]
deps = black
       flake8
commands =
    black --check AxAbsEnt
    flake8 AxAbsEnt

[testenv:docs]
deps = -rrequirements-docs.txt
commands = mkdocs build --strict
