# tools/exporters/presentation_generator.py

"""
AxAbsEnt Presentation Generator

Generates scientific presentation decks from simulation or theoretical data.
Outputs .pptx (PowerPoint) format with plots, text, and metadata.
Conforms to ontology-consistent visualization and scientific traceability.
"""

import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
from typing import Dict, Any

SLIDE_WIDTH = Inches(13.33)
SLIDE_HEIGHT = Inches(7.5)

def _add_title_slide(prs, title, subtitle):
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle


def _add_text_slide(prs, title, content):
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    textbox = slide.placeholders[1]
    textbox.text = content


def _plot_tensor(tensor: np.ndarray, output_path: str):
    plt.figure(figsize=(6, 5))
    plt.imshow(tensor, cmap='viridis', interpolation='nearest')
    plt.colorbar(label='Curvature / Entropy')
    plt.title("Tensor Field")
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()


def _add_image_slide(prs, title, image_path):
    slide_layout = prs.slide_layouts[5]
    slide = prs.slides.add_slide(slide_layout)
    title_shape = slide.shapes.title
    title_shape.text = title
    left = Inches(1)
    top = Inches(1.5)
    height = Inches(4.5)
    slide.shapes.add_picture(image_path, left, top, height=height)


def _add_footer_metadata(prs, metadata: Dict[str, Any]):
    footer_slide = prs.slides.add_slide(prs.slide_layouts[1])
    footer_slide.shapes.title.text = "Export Metadata"
    textbox = footer_slide.placeholders[1]
    text = "\n".join([f"{k}: {v}" for k, v in metadata.items()])
    textbox.text = text


def generate_presentation(data: Dict[str, Any], output_path: str) -> None:
    """
    Generate a presentation deck from a simulation or theory structure.

    Args:
        data (dict): Should include keys like:
            - title
            - description
            - tensor (optional): np.ndarray
            - results (optional): textual summary
        output_path (str): Target .pptx file path
    """
    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    title = data.get("title", "AxAbsEnt Presentation")
    subtitle = data.get("description", "Generated by AxAbsEnt Unified Engine")
    _add_title_slide(prs, title, subtitle)

    if "results" in data:
        _add_text_slide(prs, "Summary of Results", data["results"])

    if "tensor" in data and isinstance(data["tensor"], np.ndarray):
        tensor_path = output_path.replace(".pptx", "_tensor.png")
        _plot_tensor(data["tensor"], tensor_path)
        _add_image_slide(prs, "Tensor Visualization", tensor_path)

    metadata = {
        "Generated": datetime.utcnow().isoformat() + "Z",
        "Model": "Enhanced Mathematical Ontology of Absolute Nothingness",
        "Version": "1.0"
    }
    _add_footer_metadata(prs, metadata)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    prs.save(output_path)
